# https://taskfile.dev
version: "3"

vars:
  PROJECT_NAME: swimming-tuna
  BUILD_DIR: build

env:
  CGO_ENABLED: "0"

tasks:
  default:
    cmds:
      - task --list
    silent: true

  init:
    desc: Initialize development environment
    cmds:
      - echo "Installing pre-commit hooks..."
      - pre-commit install
      - echo "Installing tools..."
      - dotnet tool install --global GitVersion.Tool
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.64.8
      - go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest
      - go install github.com/goreleaser/goreleaser/v2@latest
      - go install github.com/daveshanley/vacuum@latest
      - task: repomix:install
      - pip install ruff

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run ./...

  test:
    desc: Run tests
    cmds:
      - go test -v -race ./...

  test:dotnet:
    desc: Run .NET runtime tests (includes intervention, graph/telemetry, and lifecycle reliability suites)
    cmds:
      - dotnet test project/dotnet/tests/SwarmAssistant.Runtime.Tests/SwarmAssistant.Runtime.Tests.csproj

  test:dotnet:intervention:
    desc: Run only the intervention reliability test suite
    cmds:
      - dotnet test project/dotnet/tests/SwarmAssistant.Runtime.Tests/SwarmAssistant.Runtime.Tests.csproj --filter InterventionReliabilityTests

  test:dotnet:graph:
    desc: Run only the graph and telemetry event test suite
    cmds:
      - dotnet test project/dotnet/tests/SwarmAssistant.Runtime.Tests/SwarmAssistant.Runtime.Tests.csproj --filter GraphAndTelemetryEventTests

  build:
    desc: Build the project
    cmds:
      - dotnet build project/dotnet/SwarmAssistant.sln
      - mkdir -p {{.BUILD_DIR}}
      - go build -ldflags "-s -w -X main.version=$(gitversion /showvariable SemVer)" -o {{.BUILD_DIR}}/{{.PROJECT_NAME}} .

  run:aspire:
    desc: Run the .NET Aspire AppHost orchestrator
    cmds:
      - dotnet run --project project/dotnet/src/SwarmAssistant.AppHost/SwarmAssistant.AppHost.csproj

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}

  version:
    desc: Show current version
    cmds:
      - gitversion /showvariable SemVer

  release:
    desc: Create a release
    cmds:
      - goreleaser release --clean
    preconditions:
      - sh: "[ -z \"$(git status --porcelain)\" ]"
        msg: "Working directory is not clean (staged, unstaged, or untracked changes). Please commit or stash your changes first."

  changelog:
    desc: Generate changelog
    cmds:
      - git-chglog -o CHANGELOG.md

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...
      - goimports -w .

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  # Python tasks (Ruff)
  ruff:lint:
    desc: Run Ruff linter on Python files
    cmds:
      - ruff check . --fix

  ruff:format:
    desc: Run Ruff formatter on Python files
    cmds:
      - ruff format .

  ruff:check:
    desc: Run Ruff linter without fixing
    cmds:
      - ruff check .

  # Repomix tasks
  repomix:install:
    desc: Install repomix globally
    cmds:
      - npm install -g repomix

  repomix:pack:
    desc: Pack repository into a single file using repomix
    cmds:
      - repomix

  repomix:pack:markdown:
    desc: Pack repository with Markdown output format
    cmds:
      - repomix --style markdown --output repomix-output.md

  repomix:pack:plain:
    desc: Pack repository with plain text output format
    cmds:
      - repomix --style plain --output repomix-output.txt

  repomix:pack:remote:
    desc: "Pack a remote repository (usage: task repomix:pack:remote REPO=https://github.com/user/repo)"
    cmds:
      - repomix --remote {{.REPO}}
    requires:
      vars: [REPO]

  repomix:clean:
    desc: Clean repomix output files
    cmds:
      - rm -f repomix-output.*

  # Agent skills tasks
  skills:list:
    desc: List available agent skills
    cmds:
      - echo "Available skills in .agent/skills/:"
      - ls -1 .agent/skills/ 2>/dev/null || echo "No skills found"

  skills:read:
    desc: "Read a skill (usage: task skills:read SKILL=skill-name)"
    cmds:
      - |
        if [[ ! "{{.SKILL}}" =~ ^[a-zA-Z0-9_/-]+$ ]]; then
          echo "Error: Invalid skill name '{{.SKILL}}'. Only alphanumeric characters, hyphens, underscores, and '/' are allowed." >&2
          exit 1
        fi
        SKILL_BASE=".agent/skills/{{.SKILL}}"
        if [ -d "$SKILL_BASE" ]; then
          cat "$SKILL_BASE/SKILL.md"
        elif [ -f "${SKILL_BASE}.md" ]; then
          cat "${SKILL_BASE}.md"
        elif [ -f "$SKILL_BASE" ]; then
          cat "$SKILL_BASE"
        else
          echo "Error: Skill '{{.SKILL}}' not found." >&2
          exit 1
        fi
    requires:
      vars: [SKILL]

  skills:new:
    desc: "Create a new skill directory (usage: task skills:new SKILL=skill-name)"
    cmds:
      - |
        if [[ ! "{{.SKILL}}" =~ ^[a-zA-Z0-9_-]+$ ]]; then
          echo "Error: Invalid skill name '{{.SKILL}}'. Only alphanumeric characters, hyphens, and underscores are allowed." >&2
          exit 1
        fi

        SKILL_PATH=".agent/skills/{{.SKILL}}"

        if [ -d "$SKILL_PATH" ]; then
          echo "Error: Skill '{{.SKILL}}' already exists." >&2
          exit 1
        fi

        mkdir -p "$SKILL_PATH"
        {
          echo '---'
          echo 'name: {{.SKILL}}'
          echo 'description: Description of what this skill provides and when to use it'
          echo '---'
          echo ''
          echo '# {{.SKILL}}'
          echo ''
          echo '## Overview'
          echo ''
          echo 'Describe the purpose of this skill.'
          echo ''
          echo '## Usage'
          echo ''
          echo 'Instructions for using this skill.'
          echo ''
          echo '## Examples'
          echo ''
          echo 'Provide examples if applicable.'
        } > "$SKILL_PATH/SKILL.md"
        echo "Created skill: {{.SKILL}}"
        echo "Edit $SKILL_PATH/SKILL.md to customize"
    requires:
      vars: [SKILL]

  # Model generation tasks (quicktype)
  models:generate:
    desc: Regenerate C# and TypeScript models from the OpenAPI schema
    cmds:
      - bash scripts/generate-models.sh

  models:verify:
    desc: Fail if generated model files are stale (used in CI)
    cmds:
      - bash scripts/verify-models.sh

  # OpenAPI tasks
  openapi:lint:
    desc: Validate OpenAPI spec with vacuum linter
    cmds:
      - vacuum lint project/docs/openapi/runtime.v1.yaml

  # Agent sync tasks
  agent:sync:
    desc: Sync agent skills/rules/hooks to all configured tools
    cmds:
      - python .agent/tools/sync.py --all

  agent:sync:claude:
    desc: Sync agent config to Claude Code
    cmds:
      - python .agent/tools/sync.py --adapter claude

  agent:sync:codex:
    desc: Sync agent config to Codex CLI
    cmds:
      - python .agent/tools/sync.py --adapter codex

  agent:sync:cline:
    desc: Sync agent config to Cline CLI
    cmds:
      - python .agent/tools/sync.py --adapter cline

  agent:sync:copilot:
    desc: Sync agent config to Copilot CLI
    cmds:
      - python .agent/tools/sync.py --adapter copilot

  dogfood:diagnostic:
    desc: Run dogfood diagnostic (submits real task, traces pipeline)
    cmds:
      - bash scripts/dogfood-diagnostic.sh {{.CLI_ARGS}}
