# https://taskfile.dev
version: "3"

vars:
  PROJECT_NAME: swimming-tuna
  BUILD_DIR: build

env:
  CGO_ENABLED: "0"

tasks:
  default:
    cmds:
      - task --list
    silent: true

  init:
    desc: Initialize development environment
    cmds:
      - echo "Installing pre-commit hooks..."
      - pre-commit install
      - echo "Installing tools..."
      - dotnet tool install --global GitVersion.Tool
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.64.8
      - go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest
      - go install github.com/goreleaser/goreleaser/v2@latest
      - task: repomix:install
      - pip install ruff

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run ./...

  test:
    desc: Run tests
    cmds:
      - go test -v -race ./...

  build:
    desc: Build the project
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -ldflags "-s -w -X main.version=$(gitversion /showvariable SemVer)" -o {{.BUILD_DIR}}/{{.PROJECT_NAME}} .

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}

  version:
    desc: Show current version
    cmds:
      - gitversion /showvariable SemVer

  release:
    desc: Create a release
    cmds:
      - goreleaser release --clean
    preconditions:
      - sh: "[ -z \"$(git status --porcelain)\" ]"
        msg: "Working directory is not clean (staged, unstaged, or untracked changes). Please commit or stash your changes first."

  changelog:
    desc: Generate changelog
    cmds:
      - git-chglog -o CHANGELOG.md

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...
      - goimports -w .

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  # Python tasks (Ruff)
  ruff:lint:
    desc: Run Ruff linter on Python files
    cmds:
      - ruff check . --fix

  ruff:format:
    desc: Run Ruff formatter on Python files
    cmds:
      - ruff format .

  ruff:check:
    desc: Run Ruff linter without fixing
    cmds:
      - ruff check .

  # Repomix tasks
  repomix:install:
    desc: Install repomix globally
    cmds:
      - npm install -g repomix

  repomix:pack:
    desc: Pack repository into a single file using repomix
    cmds:
      - repomix

  repomix:pack:markdown:
    desc: Pack repository with Markdown output format
    cmds:
      - repomix --style markdown --output repomix-output.md

  repomix:pack:plain:
    desc: Pack repository with plain text output format
    cmds:
      - repomix --style plain --output repomix-output.txt

  repomix:pack:remote:
    desc: "Pack a remote repository (usage: task repomix:pack:remote REPO=https://github.com/user/repo)"
    cmds:
      - repomix --remote {{.REPO}}
    requires:
      vars: [REPO]

  repomix:clean:
    desc: Clean repomix output files
    cmds:
      - rm -f repomix-output.*

  # Agent skills tasks
  skills:list:
    desc: List available agent skills
    cmds:
      - echo "Available skills in .agent/skills/:"
      - ls -1 .agent/skills/ 2>/dev/null || echo "No skills found"

  skills:read:
    desc: "Read a skill (usage: task skills:read SKILL=skill-name)"
    cmds:
      - cat .agent/skills/{{.SKILL}}/SKILL.md
    requires:
      vars: [SKILL]

  skills:new:
    desc: "Create a new skill directory (usage: task skills:new SKILL=skill-name)"
    cmds:
      - mkdir -p .agent/skills/{{.SKILL}}
      - |
        cat > .agent/skills/{{.SKILL}}/SKILL.md << 'EOF'
        ---
        name: {{.SKILL}}
        description: Description of what this skill provides and when to use it
        ---

        # {{.SKILL}}

        ## Overview

        Describe the purpose of this skill.

        ## Usage

        Instructions for using this skill.

        ## Examples

        Provide examples if applicable.
        EOF
      - echo "Created skill: {{.SKILL}}"
      - echo "Edit .agent/skills/{{.SKILL}}/SKILL.md to customize"
    requires:
      vars: [SKILL]
